version: '3'
services:
  database:
    image: "postgres:12.6"
    env_file:
      - ./.env # configure postgres
    ports:
      - "65056:5432"
    volumes:
      - ./src/container/postgresql/:/docker-entrypoint-initdb.d
      - database_data:/var/lib/postgresql/data

  data-transfer:
    build:
      context: ./src/container/
      dockerfile: ./db_data_transfer/Dockerfile
    env_file:
      - ./.env # configure postgres


  domain-collector:
    build:
      context: ./src/container/
      dockerfile: ./data_collector/Dockerfile
    env_file:
      - ./.env # configure postgres

  alexa-meta-collector:
    build:
      context: ./src/container/
      dockerfile: ./meta_collectors/alexa/Dockerfile
    env_file:
        - ./.env

  whois-meta-collector:
    build:
      context: ./src/container/
      dockerfile: ./meta_collectors/whois/Dockerfile
    env_file:
        - ./.env

  wiki-meta-collector:
    build:
      context: ./src/container/
      dockerfile: ./meta_collectors/wiki/Dockerfile
    env_file:
        - ./.env

  test-collector:
    build:
      context: ./src/container/
      dockerfile: ./test-collector/Dockerfile
    env_file:
        - ./.env

  public_api:
    build:
      context: ./src/container/public_api
    env_file:
      - ./.env # configure postgres
    ports:
      - "127.0.0.1:8050:5432"
    entrypoint: bash -c "/bin/bash"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  database_data: # named volumes can be managed easier using docker-compose
    driver: local
