version: '3'
services:
  database:
    image: "postgres:12.6"
    env_file:
      - ./.env # configure postgres
    ports:
      - "65056:5432"
    volumes:
      #- database-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
      - ./src/container/postgresql:/docker-entrypoint-initdb.d

  collector:
    build:
      context: ./src/container/data_collector
      network: host
      args:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
    env_file:
      - ./.env # configure postgres

volumes:
  database-data: # named volumes can be managed easier using docker-compose